# Generated by Django 4.2.3 on 2023-08-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_quantity_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=255, verbose_name='description'),
        ),
    ]
