# Generated by Django 4.2.3 on 2023-09-29 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=200, verbose_name='code')),
                ('offer', models.IntegerField(max_length=200, verbose_name='offer')),
                ('type', models.CharField(default='Percentage', max_length=200, verbose_name='type')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='count_in_store',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.offercode'),
        ),
    ]
