# Generated by Django 4.2.3 on 2023-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_offercode_product_count_in_store_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercode',
            name='offer',
            field=models.IntegerField(verbose_name='offer'),
        ),
    ]
