# Generated by Django 4.2.3 on 2023-09-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_offercode_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ManyToManyField(to='shop.productunit', verbose_name='unit'),
        ),
    ]
