# Generated by Django 4.2.3 on 2023-08-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_postal_code_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.province', verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterField(
            model_name='province',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(to='customers.address'),
        ),
    ]
