# Generated by Django 4.2.3 on 2023-08-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_quantity_alter_category_image_and_more'),
        ('customers', '0003_alter_city_province_alter_city_title_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=30, verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.CharField(max_length=200, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='vehicle',
            field=models.CharField(max_length=200, verbose_name='vehicle'),
        ),
    ]
