# Generated by Django 4.2.3 on 2023-09-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_orderitem_description_remove_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Checkout', 'Checkout'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('TransferPending', 'TransferPending'), ('Delivered', 'Delivered')], default='Checkout', max_length=30, verbose_name='status'),
        ),
    ]
