# Generated by Django 4.2.3 on 2023-09-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_offercode_product_count_in_store_product_created_at_and_more'),
        ('finance', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(blank=True, choices=[('CoffeeBean', 'CoffeeBean'), ('GroundCoffeeMokapot', 'GroundCoffeeMokapot'), ('GroundCoffeeHome', 'GroundCoffeeHome'), ('GroundCoffeeShop', 'GroundCoffeeShop')], max_length=200, null=True, verbose_name='package type')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='finance.orderitems'),
        ),
    ]
