# Generated by Django 4.2.3 on 2023-09-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_unit_product_unit'),
        ('finance', '0005_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.productunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.packagetype', verbose_name='package type'),
        ),
    ]
